name: home_work
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.1.5

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  bottom_sheet: ^4.0.0
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.3
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get_it: ^7.6.0
  intl: ^0.18.1
  permission_handler: ^11.0.0
  provider: ^6.0.5
  photo_manager: ^2.7.1
  path: ^1.8.3
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  vector_graphics: ^1.1.7
  local_auth: ^2.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/app_icons/
    - assets/drawer_icons/
    - assets/message_category_icons/
    - assets/notes_icons/

flutter_native_splash:
  image: assets/app_icons/splash_icon.png
  android: true
  ios: true
  # android_12: 
  #   image: assets/app_icons/splash_icon_android12.png
  #   color: "#0xFFf6f9ff"
  #   icon_background_color: "0xFFf6f9ff"